[tool.poetry]
name = "rcds"
version = "0.0.1"
description = "An automated CTF challenge deployment tool"
readme = "README.rst"
authors = ["redpwn <contact@redpwn.net>"]
homepage = "https://rdeploy.redpwn.net"
repository = "https://github.com/redpwn/rdeploy"
license = "BSD-3-Clause"
packages = [
    { include = "rcds" },
]

[tool.poetry.dependencies]
python = "^3.6"
pyyaml = "^5.3.1"
pathspec = "^0.7.0"
docker = "^4.2.0"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
pre-commit = { version = "^2.2.0", python = "^3.6.1" }
black = "^19.10b0"
pytest = "^5.4.1"
coverage = "^5.0.4"
mypy = "^0.770"
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.4"
pytest-datadir = "^1.3.1"
sphinx = "^3.0.1"
sphinx_rtd_theme = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
