{% import '_helpers.jinja' as helpers with context %}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: {{ container.name }}
  labels:
    {{ helpers.common_labels() | indent(4) }}
    {{ helpers.container_labels() | indent(4) }}
spec:
  replicas: {{ container.config.replicas }}
  selector:
    matchLabels:
      {{ helpers.common_labels() | indent(6) }}
      {{ helpers.container_labels() | indent(6) }}
  template:
    metadata:
      labels:
        {{ helpers.common_labels() | indent(8) }}
        {{ helpers.container_labels() | indent(8) }}
    spec:
      containers:
        - name: container
          image: {{ container.config.image }}
          {% if container.config.ports %}
          ports:
          {% for port in container.config.ports %}
            - containerPort: {{ port }}
              name: port-{{ port }}
          {% endfor %}
          {% endif %}
          {% if container.config.environment %}
          env:
          {% for name, value in container.config.environment.items() %}
            - name: {{ name }}
              value: {{ value | quote }}
          {% endfor %}
          {% endif %}
          {% if container.config.resources %}
          resources:
            {{ container.config.resources | yaml(12) }}
          {% endif %}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: {{ container.config.readOnlyRootFilesystem }}
          {% if container.config.tmpfsMounts | first is defined %}
          volumeMounts:
            {% for tmpfsMount in container.config.tmpfsMounts %}
            - name: {{ tmpfsMount }}
              mountPath: {{ tmpfsMount }}
            {% endfor %}
          {% endif %}
          {% if container.healthcheck.enabled %}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 45281
            initialDelaySeconds: 45
            timeoutSeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 45281
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
        - name: healthcheck
          image: {{ container.healthcheck.config.image }}
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 50m
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
        {% endif %}
      {% if container.config.tmpfsMounts | first is defined %}
      volumes:
        {% for tmpfsMount in container.config.tmpfsMounts %}
        - name: {{ tmpfsMount }}
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
        {% endfor %}
      {% endif %}
      automountServiceAccountToken: false
      enableServiceLinks: false
      {% if options.tolerations %}
      tolerations:
        {{ options.tolerations | yaml(8) }}
      {% endif %}
      {% if options.affinity %}
      affinity:
        {{ options.affinity | yaml(8) }}
      {% endif %}
