{% import '_helpers.jinja' as helpers with context %}
{% if container.expose %}
{% set tcpPorts = container.expose|selectattr("tcp", "defined")|list %}
{% if tcpPorts | first is defined %}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  namespace: {{ namespace }}
  name: {{ container.name }}
  labels:
    {{ helpers.common_labels() | indent(4) }}
    {{ helpers.container_labels() | indent(4) }}
  {% if options.annotations and options.annotations.ingressroutetcp %}
  annotations:
    {{ options.annotations.ingressroutetcp | yaml(4) }}
  {% endif %}
spec:
  entryPoints:
    - chal
  routes:
  {% for tcpPort in tcpPorts %}
    - match: HostSNI(`{{ tcpPort.tcp }}`)
      services:
        - name: {{ container.name }}
          port: {{ tcpPort.target }}
  {% endfor %}
  tls: {}
{% endif %}
{% endif %}
