{% import '_helpers.jinja' as helpers with context %}
{% if container.expose %}
{% set httpPorts = container.expose|selectattr("http", "defined")|list %}
{% if httpPorts | first is defined %}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: {{ namespace }}
  name: {{ container.name }}
  labels:
    {{ helpers.common_labels() | indent(4) }}
    {{ helpers.container_labels() | indent(4) }}
  {% if options.annotations and options.annotations.ingressroute %}
  annotations:
    {{ options.annotations.ingressroute | yaml(4) }}
  {% endif %}
spec:
  entryPoints:
    - https
  routes:
  {% for httpPort in httpPorts %}
    - match: Host(`{{ httpPort.http }}`)
      kind: Rule
      services:
        - name: {{ container.name }}
          port: {{ httpPort.target }}
  {% endfor %}
  tls: {}
{% endif %}
{% endif %}
